# SPDX-FileCopyrightText: Magenta ApS <https://magenta.dk>
# SPDX-License-Identifier: MPL-2.0
---
root_organisation:
  municipality_code: null

facets:
  org_unit_type:
    Enhed:
      title: "Enhed"
      scope: "TEXT"
  org_unit_address_type:
    Contact:
      title: "Henvendelsessted"
      scope: "DAR"
    Location:
      title: "Lokation"
      scope: "DAR"
  engagement_type:
    ansat:
      title: "Ansat"
      scope: "TEXT"
  engagement_job_function:
    tester:
      title: "Tester"
      scope: "TEXT"
    ninja:
      title: "Ninja"
      scope: "TEXT"
  employee_address_type:
    email:
      title: "Email"
      scope: "EMAIL"
    mobile:
      title: "Mobil"
      scope: "PHONE"
    landline:
      title: "Telefon"
      scope: "PHONE"

it_systems:
  "Active Directory": "Active Directory"
  FK-ORG-UUID: "FK-org uuid"
